import { Footer } from "@/components/footer/Footer"
import { Header } from "@/components/header/Header"
import type { Metadata } from "next"
import { Geist } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={`${geistSans.variable} h-full`}>
			<body className="min-h-screen bg-slate-50 text-slate-900 antialiased dark:bg-slate-950 dark:text-slate-100">
				<div className="mx-auto flex min-h-screen max-w-7xl flex-col px-4 py-4 sm:px-6 lg:px-8">
					<Header />
					<main className="flex-1 px-2 py-4 sm:px-0">{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	)
}
